{
 "title": "Kubernetes",
 "description": "Summary metrics about containers running on Kubernetes",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(up{job=\"backend\", node=\"Kubernetes\"}, node_name)"
   },
   {
    "name": "node",
    "label": "Node name",
    "query": "label_values(kube_node_info{job=\"kubernetes-exporter\", node_name=~\"$cluster\"},node)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_namespace_labels{job=\"kubernetes-exporter\", node=\"Kubernetes\", node_name=~\"$cluster\"},namespace)"
   }
  ]
 },
 "panels": [
  { "title": "Cluster Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster Pod Usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_info{job=\"kubernetes-exporter\", node_name=~\"$cluster\", node=~\"$node\"}) / sum(kube_node_status_allocatable_pods{job=\"kubernetes-exporter\", node_name=~\"$cluster\", node=~\".*\"})"
    }
   ]
  },
  {
   "title": "Cluster CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{job=\"kubernetes-exporter\", node_name=~\"$cluster\", node=~\"$node\"}) / sum(kube_node_status_allocatable_cpu_cores{job=\"kubernetes-exporter\", node_name=~\"$cluster\", node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Cluster Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{job=\"kubernetes-exporter\", node_name=~\"$cluster\", node=~\"$node\"}) / sum(kube_node_status_allocatable_memory_bytes{job=\"kubernetes-exporter\", node_name=~\"$cluster\", node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Cluster Pod Capacity",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "pods" }
   ],
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable_pods{job=\"kubernetes-exporter\", node_name=~\"$cluster\", node=~\"$node\"})",
     "legendFormat": "allocatable"
    },
    {
     "expr": "sum(kube_node_status_capacity_pods{job=\"kubernetes-exporter\", node_name=~\"$cluster\", node=~\"$node\"})",
     "legendFormat": "capacity"
    },
    {
     "expr": "sum(kube_pod_info{job=\"kubernetes-exporter\", node_name=~\"$cluster\", node=~\"$node\"})",
     "legendFormat": "requested"
    }
   ]
  },
  {
   "title": "Cluster CPU Capacity",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity_cpu_cores{job=\"kubernetes-exporter\", node_name=~\"$cluster\", node=~\"$node\"})",
     "legendFormat": "allocatable"
    },
    {
     "expr": "sum(kube_node_status_allocatable_cpu_cores{job=\"kubernetes-exporter\", node_name=~\"$cluster\", node=~\"$node\"})",
     "legendFormat": "capacity"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{job=\"kubernetes-exporter\", node_name=~\"$cluster\", node=~\"$node\"})",
     "legendFormat": "requested"
    }
   ]
  },
  {
   "title": "Cluster Mem Capacity",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable_memory_bytes{job=\"kubernetes-exporter\", node_name=~\"$cluster\", node=~\"$node\"})",
     "legendFormat": "allocatable"
    },
    {
     "expr": "sum(kube_node_status_capacity_memory_bytes{job=\"kubernetes-exporter\", node_name=~\"$cluster\", node=~\"$node\"})",
     "legendFormat": "capacity"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{job=\"kubernetes-exporter\", node_name=~\"$cluster\", node=~\"$node\"})",
     "legendFormat": "requested"
    }
   ]
  },
  { "title": "Deployments", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Deployment Replicas - Up To Date",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas{job=\"kubernetes-exporter\", node_name=~\"$cluster\", namespace=~\"$namespace\"}",
     "legendFormat": "{{ deployment }}"
    }
   ]
  },
  {
   "title": "Deployment Replicas",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 11 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas{job=\"kubernetes-exporter\", node_name=~\"$cluster\", namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Deployment Replicas - Updated",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 11 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_updated{job=\"kubernetes-exporter\", node_name=~\"$cluster\", namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Deployment Replicas - Unavailable",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 11 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_unavailable{job=\"kubernetes-exporter\", node_name=~\"$cluster\", namespace=~\"$namespace\"})"
    }
   ]
  },
  { "title": "Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Number Of Nodes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 17 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_node_info{job=\"kubernetes-exporter\", node_name=~\"$cluster\", node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Nodes Out of Disk",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{job=\"kubernetes-exporter\", condition=\"OutOfDisk\", node_name=~\"$cluster\", node=~\"$node\", status=\"true\"})"
    }
   ]
  },
  {
   "title": "Nodes Unavailable",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_spec_unschedulable{job=\"kubernetes-exporter\", node_name=~\"$cluster\", node=~\"$node\"})"
    }
   ]
  },
  { "title": "Pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Pods Running",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 21 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{job=\"kubernetes-exporter\", node_name=~\"$cluster\", namespace=~\"$namespace\", phase=\"Running\"})"
    }
   ]
  },
  {
   "title": "Pods Pending",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 21 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{job=\"kubernetes-exporter\", node_name=~\"$cluster\", namespace=~\"$namespace\", phase=\"Pending\"})"
    }
   ]
  },
  {
   "title": "Pods Failed",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 24 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{job=\"kubernetes-exporter\", node_name=~\"$cluster\", namespace=~\"$namespace\", phase=\"Failed\"})"
    }
   ]
  },
  {
   "title": "Pods Succeeded",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 24 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{job=\"kubernetes-exporter\", node_name=~\"$cluster\", namespace=~\"$namespace\", phase=\"Succeeded\"})"
    }
   ]
  },
  {
   "title": "Pods Unknown",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 24 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{job=\"kubernetes-exporter\", node_name=~\"$cluster\", namespace=~\"$namespace\", phase=\"Unknown\"})"
    }
   ]
  },
  { "title": "Containers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Containers Running",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 28 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{job=\"kubernetes-exporter\", node_name=~\"$cluster\", namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Containers Waiting",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 28 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_waiting{job=\"kubernetes-exporter\", node_name=~\"$cluster\", namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Containers Terminated",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 28 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_terminated{job=\"kubernetes-exporter\", node_name=~\"$cluster\", namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Containers Restarts (Last 30 Minutes)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 28 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(delta(kube_pod_container_status_restarts_total{job=\"kubernetes-exporter\", node_name=~\"$cluster\", namespace=~\"$namespace\"}[30m]))"
    }
   ]
  },
  {
   "title": "CPU Cores Requested by Containers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 31 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{job=\"kubernetes-exporter\", node_name=~\"$cluster\", namespace=~\"$namespace\", node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Memory Requested By Containers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 31 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{job=\"kubernetes-exporter\", node_name=~\"$cluster\", namespace=~\"$namespace\", node=~\"$node\"})"
    }
   ]
  }
 ]
}