#!/usr/bin/env python3
"""Simple helper script for starting an IM (infrastructure manager)
instance for development purpose.

The recommended way to launch an IM instance is Docker.
Read the IM docs for details: https://imdocs.readthedocs.io/en/latest/

.. code:: bash

    $ support/im
    $ curl -s localhost:8800/version
    1.13.0

"""
from argparse import ArgumentParser
from functools import reduce
import os


def main(name, port):
    os.execvp(
        "docker",
        ["docker", "run", "-d"] \
            + reduce(lambda a, b: a+b, [["-p", f"{x}:8800"] for x in port]) \
            + ["--name", name, "docker.io/grycap/im"],
    )


if __name__ == "__main__":
    parser = ArgumentParser(description=("IM instance for development purposes"))
    parser.add_argument(
        "--name",
        default="im",
        help="human-readable name for this IM docker container. Default: im",
    )
    parser.add_argument(
        "--port",
        type=str, nargs='*',
        default=["127.0.0.1:8800", "[::1]:8800"],
        help=("IM instance port to listen on. Optionally an IP address can be "
              "prepended with a semicolon. Multiple values can be specified. "
              "Default: 127.0.0.1:8800, [::1]:8800"),
    )

    args = vars(parser.parse_args())
    main(**args)
