# This bootstrap file adds the Prometheus metrics used by the ``support/prometheus``
# script (used in tests), as well as a provider to connect to the Prometheus server
# locally.
#
# These resources can be loaded using the ``bootstrap`` script.

##########################
### Prometheus Metrics ###
##########################

api: core
kind: GlobalMetric
metadata:
  name: heat_demand_zone_1
spec:
  allowed_values: []
  max: 5.0
  min: 0.0
  provider:
    metric: heat_demand_zone_1
    name: prometheus

---


api: core
kind: GlobalMetric
metadata:
  name: heat_demand_zone_2
spec:
  allowed_values: []
  max: 5.0
  min: 0.0
  provider:
    metric: heat_demand_zone_2
    name: prometheus

---


api: core
kind: GlobalMetric
metadata:
  name: heat_demand_zone_3
spec:
  allowed_values: []
  max: 5.0
  min: 0.0
  provider:
    metric: heat_demand_zone_3
    name: prometheus

---


api: core
kind: GlobalMetric
metadata:
  name: heat_demand_zone_4
spec:
  allowed_values: []
  max: 5.0
  min: 0.0
  provider:
    metric: heat_demand_zone_4
    name: prometheus

---


api: core
kind: GlobalMetric
metadata:
  name: heat_demand_zone_5
spec:
  allowed_values: []
  max: 5.0
  min: 0.0
  provider:
    metric: heat_demand_zone_5
    name: prometheus

---

api: core
kind: GlobalMetric
metadata:
  name: heat_demand_zone_6
spec:
  allowed_values: [0,1,4,5]
  max: 5.0
  min: 0.0
  provider:
    metric: heat_demand_zone_6
    name: prometheus

---


####################################
### Prometheus Metrics Providers ###
####################################

api: core
kind: GlobalMetricsProvider
metadata:
  name: prometheus
spec:
  type: prometheus
  prometheus:
    url: http://localhost:9090
