---
- name: Create and start Prometheus Dummy Exporter container
  docker_container:
    name: "{{ exporter_dummy_container_name }}"
    image: "{{ exporter_dummy_image_name }}:{{ exporter_dummy_image_tag }}"
    command: "-default_ip {{ exporter_dummy_api_ip }} -default_port {{ exporter_dummy_api_port }}"
    detach: yes
    exposed_ports:
      - "{{ exporter_dummy_port }}:{{ exporter_dummy_port }}"
      - "{{ exporter_dummy_api_port }}:{{ exporter_dummy_api_port }}"
    networks:
      - name: "{{ docker_network }}"
        ipv4_address: "{{ exporter_dummy_ip }}"
    state: started
