---
- name: Create configuration directory
  file:
    path: "{{ nginx_config_directory }}"
    state: directory
    mode: u=rwx,g=rx,o=rx

- name: Create reverse proxy configuration directory
  file:
    path: "{{ nginx_proxy_config_directory }}"
    state: directory
    mode: u=rwx,g=rx,o=rx

- name: Create ssl cert configuration directory
  file:
    path: "{{ nginx_ssl_config_directory }}"
    state: directory
    mode: u=rwx,g=rx,o=rx

- name: Put the nginx.conf file in place
  become: yes
  copy:
    content: "{{ nginx_conf }}"
    dest: "{{ nginx_config_directory }}nginx.conf"
    mode: u=rw,g=r,o=r
  notify:
    - nginx_reload_config

- name: Put the reverse-proxy.conf file in place
  template:
    src: "{{ item }}.j2"
    dest: "{{ nginx_proxy_config_directory }}{{ item }}"
  with_items:
    - nginx-proxy.conf
  notify:
    - nginx_reload_config

- name: Generate a Self Signed OpenSSL certificate
  command: openssl req \
    -x509 \
    -newkey rsa:4096 \
    -keyout "{{ nginx_ssl_config_directory }}key.pem" \
    -out "{{ nginx_ssl_config_directory }}cert.pem" \
    -days 365 \
    -nodes \
    -subj "/C=DE/ST=Saxony/L=Dresden/O=CLOUD&HEAT Technologies/OU=Krake/CN=Prometheus Signing"
  args:
    creates: "{{ nginx_ssl_config_directory }}cert.pem"
