---
- name: Create and start Nginx container
  docker_container:
    name: "{{ nginx_container_name }}"
    image: "{{ nginx_image_name }}:{{ nginx_image_tag }}"
    command: "{{ nginx_command }}"
    detach: yes
    published_ports: "{{ nginx_published_port }}:{{ nginx_published_port }}"
    restart_policy: always
    volumes:
      - "{{ nginx_config_directory}}nginx.conf:/etc/nginx/nginx.conf"
      - "{{ nginx_proxy_config_directory }}nginx-proxy.conf:/etc/nginx/conf.d/nginx-proxy.conf"
      - "{{ nginx_ssl_config_directory }}:/etc/nginx/ssl"
    state: started
    networks:
      - name: "{{ docker_network }}"
        ipv4_address: "{{ nginx_proxy_ip }}"
  register: nginx_container
