include:

  - local: gitlab-ci/build-ci-images.yml
    rules:
      - if: $RUN_CREATE_IMAGES == "True" && $RUN_CI_PIPELINE == "False" && $CI_PIPELINE_SOURCE == "schedule"
      - if: $CI_PIPELINE_SOURCE == "merge_request_event"
        changes:
          - ./gitlab-ci/build-ci-images.yml
          - ./gitlab-ci/Dockerfile_ansible_runner
          - ./gitlab-ci/docker/test-image/Dockerfile

  - local: gitlab-ci/krake-ci-pipeline.yml
    rules:
      - if: $RUN_CI_PIPELINE == "True"

  - local: gitlab-ci/cleanup_krake_os_project.yml
    rules:
      - if: $RUN_CLEAN_OS_PROJECT == "True" && $RUN_CI_PIPELINE == "False" && $CI_PIPELINE_SOURCE == "schedule"
