stages:
  - test

job1:
  stage: test
  image: python:3.6
  script:
    - |
      if [[ -z "$CORE_MEMBERS" ]]; then
        echo "CORE_MEMBERS need to be defined"
        exit 1
      fi
    - |
      if [[ $GITLAB_USER_LOGIN == *"$CORE_MEMBERS"* ]]; then
        echo "core member";
      else
        echo "no core member";
      fi
  tags:
    - docker
