include:

  - local: ci/build-ci-images.yml
    rules:
      - if: $RUN_CREATE_IMAGES == "True" && $RUN_CI_PIPELINE == "False" && $CI_PIPELINE_SOURCE == "schedule"
      - if: $CI_PIPELINE_SOURCE == "merge_request_event"
        changes:
          - ./ci/build-ci-images.yml
          - ./ci/Dockerfile_ansible_runner
          - ./ci/docker/test-image/Dockerfile

  - local: ci/main-ci.yml
    rules:
      - if: $RUN_CI_PIPELINE == "True"

  - local: ci/cleanup-project.yml
    rules:
      - if: $RUN_CLEAN_OS_PROJECT == "True" && $RUN_CI_PIPELINE == "False" && $CI_PIPELINE_SOURCE == "schedule"
