repos:
- repo: https://github.com/python/black
  rev: 24.2.0
  hooks:
  - id: black
    files: ^(krake|rok)/
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: trailing-whitespace
  - id: fix-byte-order-marker
  - id: end-of-file-fixer
  - id: check-added-large-files
- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.1.13
  hooks:
  - id: forbid-tabs
    files: ^(krake|rok)/
- repo: https://github.com/pycqa/flake8
  rev: 7.0.0
  hooks:
  - id: flake8
    files: ^(krake|rok)/
