---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-demo
spec:
  cascade_policy: MIGRATE
  selector:
    matchLabels:
      app: echo
  template:
    metadata:
      labels:
        app: echo
    spec:
      containers:
      - name: echo
        image: registry.k8s.io/echoserver:1.10
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: echo-demo
spec:
  #~ cascade_policy: DELETE
  cascade_policy: MIGRATE
  type: NodePort
  selector:
    app: echo
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
