# This custom observer schema observed the `spec.replicas` field, though it is not
# present in the 'echo-demo.yaml' manifest. It doesn't observe the image of the first
# container `spec.template.spec.containers[0].image`, though it is defined in the
# 'echo-demo.yaml' manifest.
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-demo
  namespace: null
spec:
  replicas: null
  selector:
    matchLabels:
      app: null
  template:
    metadata:
      labels:
        app: null
    spec:
      containers:
      - name: null
        ports:
        - containerPort: null
        - observer_schema_list_min_length: 1
          observer_schema_list_max_length: 1
      - observer_schema_list_min_length: 1
        observer_schema_list_max_length: 1
---
apiVersion: v1
kind: Service
metadata:
  name: echo-demo
  namespace: null
spec:
  type: null
  selector:
    app: null
  ports:
  - port: null
    protocol: null
    targetPort: null
  - observer_schema_list_min_length: 1
    observer_schema_list_max_length: 1
