---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv
  labels:
    type: local
spec:
  storageClassName: pv-demo
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/ubuntu/pv"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc
spec:
  storageClassName: pv-demo
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: pvc-pod
spec:
  containers:
  - image: alpine
    imagePullPolicy: IfNotPresent
    name: pvc-container

    command: ['sh', '-c', 'sleep 60; while true; do date >> /pv/test.txt; cat /pv/test.txt; sleep 60; done;']

    volumeMounts:
      - mountPath: "/pv"
        name: pvc-name

  volumes:
    - name: pvc-name
      persistentVolumeClaim:
        claimName: pvc
