apiVersion: v1
kind: ConfigMap
metadata:
  name: keystone-auth-policy
  namespace: kube-system
data:
  policies: |
    [
      {
        "resource": {
          "verbs": ["*"],
          "resources": ["*"],
          "version": "*",
          "namespace": "*"
        },
        "match": [
          {
            "type": "role",
            "values": ["_member_"]
          },
          {
            "type": "project",
            "values": ["demo"]
          }
        ]
      }
    ]
