etcd:
  host: 127.0.0.1
  port: 2379

log:
  level: INFO

# Anonymous authentication
auth:
  kind: anonymous
  name: system

# # Keystone authentication
# auth:
#   kind: keystone
#   endpoint: http://localhost:5000/v3

controllers:

  scheduler:
    api_endpoint: http://localhost:8080
    worker_count: 5

  kubernetes:
    api_endpoint: http://localhost:8080
    worker_count: 5
