---
apiVersion: v1
kind: Namespace
metadata:
  name: development
  labels:
    environment: development
    app.kubernetes.io/instance: etcd-zeutcr
    app.kubernetes.io/version: "1.0.1"
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/part-of: krake
