# OpenStack Heat template parameters
floating_ip: false
flavor: S

# OpenStack networks have MTU value of 1450
docker_daemon_mtu: 1450

# Krake Docker image
krake_image_uid: 17890

# Configuration parameters
api_host: krake-api
api_port: 8443

## etcd database parameters
# address and port for the etcd container
etcd_host: krake-db
etcd_port: 2379
etcd_peer_port: 2380

# Authentication-related parameters
enable_tls: true
cert_dir: '/etc/krake/certs'
# cors_origin: "example.com"
allow_anonymous: false
# keystone
keystone_authentication_enabled: false
keystone_authentication_endpoint: "http://localhost:5000/v3"
# keycloak
keycloak_authentication_enabled: false
keycloak_authentication_endpoint: "http://localhost:9080"
keycloak_authentication_realm: "krake"
# static
static_authentication_enabled: false
static_authentication_username: "system:admin"

# Authorization-related parameters
authorization_mode: RBAC

## Controllers parameters
worker_count: 5
debounce: 1.0
reschedule_after: 60
stickiness: 0.1
poll_interval: 30

# "Complete" Hook-related parameters
complete_hook_user: "system:complete-hook"
complete_hook_cert_dest: "/etc/krake_cert"
complete_hook_env_token: "KRAKE_TOKEN"
complete_hook_env_complete: "KRAKE_COMPLETE_URL"

# Let the external endpoint being computed automatically using the private IP of the
# Krake application VM and the port used by the Krake API.
use_private_ip: false
# external_endpoint: https://krake.host:1234
