# OpenStack Heat template parameters
floating_ip: false
flavor: S

# Configuration parameters
api_host: krake-api
api_port: 8080

## etcd database parameters
# address and port for the etcd container
etcd_host: krake-db
etcd_port: 2379
etcd_peer_port: 2380

# Set TLS to enabled on all Krake components.
# The certificates have to be added in '/etc/krake/certs' on the VM.
enable_tls: false

## Controllers parameters
worker_count: 5
debounce: 1.0

# OpenStack networks have MTU value of 1450
docker_daemon_mtu: 1450
