heat_template_version: 2018-03-02

description: >
  Deploy a DevStack instance and configure a route on the external router

parameters:

  central_idp_priv_ip:
    type: string
    description: IP of the Central Identity Provider
    default: 185.128.119.16

  create_floating_ip:
    type: boolean
    default: false
    description: Control whether to create a floating IP for the DevStack instance or not.

  devstack_flavor:
    type: string
    description: Name of the flavor to use for the DevStack instance
    default: L.mem+

  devstack_id:
    type: string
    description: DevStack ID in the Development Environment - Required

  devstack_secgroup:
    type: comma_delimited_list
    default: default
    description: List of security group to use for DevStack instance access

  git_branch:
    type: string
    description: Name of the git branch to clone on DevStack.
    default: master

  key_name:
    type: string
    description: Name of a KeyPair to enable SSH access to the instance
    default: matthiasgoerens

  krake_network:
    type: string
    default: krake-network
    description: Name of the private network used for Krake and DevStack instances
  
  krake_subnet:
    type: string
    default: krake-subnet
    description: Name of the private subnet network for the compute server

  openstack_public_network:
    type: string
    default: shared-public-IPv4
    description: Name of the public network on which to associate a floating IP for DevStack

  router_uuid:
    type: string
    description: UUID of the external router used for the krake-private network
    default: 6288d421-8720-4f12-9699-71a148cf7979

resources:

  devstack_public_port:
    type: OS::Neutron::Port
    properties:
      name: 
        str_replace:
          template: Devstack Port devstack_id
          params:
            devstack_id: { get_param: devstack_id }
      network_id: { get_param: krake_network }
      fixed_ips:
      - subnet_id: { get_param: krake_subnet }
      security_groups: { get_param: devstack_secgroup }
      allowed_address_pairs:
      - ip_address:
          str_replace:
            template: 172.16.devstack_id.0/24
            params:
              devstack_id: { get_param: devstack_id }

  routing_rule:
    type: OS::Neutron::ExtraRoute
    properties:
      destination:
        str_replace:
          template: 172.16.devstack_id.0/24
          params:
            devstack_id: { get_param: devstack_id } 
      nexthop: {get_attr: [devstack_public_port, fixed_ips, 0, ip_address]}
      router_id: { get_param: router_uuid }

  floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network_id: { get_param: openstack_public_network }
      port_id: { get_resource: devstack_public_port }
    condition:
      equals:
      - get_param: create_floating_ip
      - true

  install_devstack:
    type: OS::Heat::SoftwareConfig
    properties:
      group: ungrouped
      config:
        str_replace:
          template: {get_file: cloud-init/install_devstack.sh}
          params:
            "$DEVSTACK_ID": { get_param: devstack_id }


  configure_federation:
    type: OS::Heat::SoftwareConfig
    properties:
      group: ungrouped
      config:
        str_replace:
          template: {get_file: cloud-init/configure_fed.sh}
          params:
            "$DEVSTACK_ID": {get_param: devstack_id}
            "$CENTRAL_IDP_IP": {get_param: central_idp_priv_ip}
            "$GIT_BRANCH": {get_param: git_branch}

  install_prometheus:
    type: OS::Heat::SoftwareConfig
    properties:
      group: ungrouped
      config: {get_file: cloud-init/install_prometheus.sh}

  devstack_cloud_init:
    type: OS::Heat::MultipartMime
    properties:
      parts:
      - config: {get_resource: install_devstack}
      - config: {get_resource: configure_federation}
      - config: {get_resource: install_prometheus}

  devstack_vm:
    type: OS::Nova::Server
    properties:
      name: 
        str_replace:
          template: Devstack VM devstack_id
          params:
            devstack_id: { get_param: devstack_id }
      flavor: { get_param: devstack_flavor }
      image: "35e19d60-2ebd-11e9-9c91-ebc42c7648d6"  # Ubuntu 16.04 LTS x64
      key_name: { get_param: key_name }
      networks:
      - port: { get_resource: devstack_public_port } 
      user_data_format: RAW
      user_data:
        get_resource: devstack_cloud_init

outputs:
  instance_ip:
    description: IP address of the deployed compute instance
    value: { get_attr: [devstack_vm, first_address] }
