- name: Debug krake resources
  debug:
    msg: "Reads out clusters, global metric providers, and metrics registered in krake"

- name: Show resources currently present in krake
  block:

   - name: Get cluster
     command: "krakectl kube cluster list -o json"
     register: krakectl_response
   - name: Extract cluster infos from krakectl response
     ansible.builtin.set_fact:
       cluster_list: "{{ (krakectl_response.stdout | from_json ) }}"
   - name: Debug cluster
     debug:
       msg: "{{ item.metadata.name }}"
     with_items: "{{ cluster_list }}"

   - name: Get gmp
     command: "krakectl core gmp list -o json"
     register: krakectl_response
   - name: Extract gmp infos from krakectl response
     ansible.builtin.set_fact:
       gmp_list: "{{ (krakectl_response.stdout | from_json ) }}"
   - name: Debug gmp
     debug:
       msg: "{{ item.metadata.name }}"
     with_items: "{{ gmp_list }}"

   - name: Get mp
     command: "krakectl core mp list -o json"
     register: krakectl_response
   - name: Extract mp infos from krakectl response
     ansible.builtin.set_fact:
       mp_list: "{{ (krakectl_response.stdout | from_json ) }}"
   - name: Debug mp
     debug:
       msg: "{{ item.metadata.name }}"
     with_items: "{{ mp_list }}"
