- name: Delete krake resources
  debug:
    msg: "Deletes apps, clusters, GlobalMetrics, GlobalMetricsProviders, MetricsProviders and Metrics registered in krake"

- name: Show resources currently present in krake
  block:

    - name: Get apps
      command: "krakectl kube app list -o json"
      register: krakectl_response
    - name: Extract app names from krakectl response
      ansible.builtin.set_fact:
        app_list: "{{ (krakectl_response.stdout | from_json ) }}"
    - name: Delete app
      command: "krakectl kube app delete {{ item.metadata.name }}"
      with_items: "{{ app_list }}"


    - name: Get clusters
      command: "krakectl kube cluster list -o json"
      register: krakectl_response
    - name: Extract cluster names from krakectl response
      ansible.builtin.set_fact:
        cluster_list: "{{ (krakectl_response.stdout | from_json ) }}"
    - name: Delete cluster
      command: "krakectl kube cluster delete {{ item.metadata.name }}"
      with_items: "{{ cluster_list }}"


    - name: Get GlobalMetrics
      command: "krakectl core gm list -o json"
      register: krakectl_response
    - name: Extract gm names from krakectl response
      ansible.builtin.set_fact:
        gm_list: "{{ (krakectl_response.stdout | from_json ) }}"
    - name: Delete GlobalMetrics
      command: "krakectl core gm delete {{ item.metadata.name }}"
      with_items: "{{ gm_list }}"


    - name: Get GlobalMetricsProviders
      command: "krakectl core gmp list -o json"
      register: krakectl_response
    - name: Extract gmp names from krakectl response
      ansible.builtin.set_fact:
        gmp_list: "{{ (krakectl_response.stdout | from_json ) }}"
    - name: Delete GlobalMetricsProvider
      command: "krakectl core gmp delete {{ item.metadata.name }}"
      with_items: "{{ gmp_list }}"


    - name: Get Metrics
      command: "krakectl core metric list -o json"
      register: krakectl_response
    - name: Extract metric namesfrom krakectl response
      ansible.builtin.set_fact:
        m_list: "{{ (krakectl_response.stdout | from_json ) }}"
    - name: Delete Metrics
      command: "krakectl core metric delete {{ item.metadata.name }}"
      with_items: "{{ m_list }}"


    - name: Get MetricProviders
      command: "krakectl core mp list -o json"
      register: krakectl_response
    - name: Extract mp infos from krakectl response
      ansible.builtin.set_fact:
        mp_list: "{{ (krakectl_response.stdout | from_json ) }}"
    - name: Delete Metrics
      command: "krakectl core mp delete {{ item.metadata.name }}"
      with_items: "{{ mp_list }}"
