version: "2"

services:

  mysqld-exporter:
    container_name: mysqld-exporter
    image: prom/mysqld-exporter
    hostname: mysqld-exporter
    tty: true
    restart: always
    depends_on:
      - krake_db
    environment:
      - DATA_SOURCE_NAME=exporter:${MYSQL_DEFAULT_PASS}@(krake_db:3306)/
    command:
      - --collect.global_status
      - --collect.global_variables
      - --collect.slave_status
      - --collect.binlog_size
      - --collect.info_schema.innodb_metrics
      - --collect.auto_increment.columns
      - --collect.info_schema.userstats
      - --collect.info_schema.tablestats
      - --collect.info_schema.tables
      - --collect.info_schema.query_response_time
      - --collect.info_schema.processlist
      - --collect.perf_schema.eventsstatements
      - --collect.perf_schema.indexiowaits
      - --collect.perf_schema.tableiowaits
      - --collect.perf_schema.tablelocks
      - --collect.perf_schema.file_events
      - --collect.perf_schema.eventswaits
    networks:
      krake_net:
        ipv4_address: 172.25.0.8

  cadvisor:
    container_name: cadvisor
    image: google/cadvisor:latest
    hostname: cadvisor
    tty: true
    restart: always
    volumes:
      # Configuration of volumes is taken from official cAdvisor documentation:
      # https://github.com/google/cadvisor/blob/master/README.md
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    networks:
      krake_net:
        ipv4_address: 172.25.0.9

  krake_nginx:
    container_name: krake_nginx
    image: krake_nginx
    build:
      context: krake_nginx
    hostname: docker_krake_nginx
    tty: true
    restart: always
    depends_on:
      - krake_api_ctrl
    volumes:
      # Docker compose relative path is interpreted as relative to the location of the Docker compose file.
      # https://docs.docker.com/compose/compose-file/compose-file-v2/
      - ./krake_nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
    ports:
      - 80:80
      - 443:443
    networks:
      krake_net:
        ipv4_address: 172.25.0.10

  krake_db:
    container_name: krake_db
    image: mariadb:10.0-xenial
    hostname: docker_krake_db
    tty: true
    restart: always
    volumes:
     - ./krake_db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_DEFAULT_PASS}
    networks:
      krake_net:
        ipv4_address: 172.25.0.11

  krake_rabbit:
    container_name: krake_rabbit
    image: krake_rabbit
    build:
      context: krake_rabbit
    hostname: docker_krake_rabbit
    tty: true
    restart: always
    networks:
      krake_net:
        ipv4_address: 172.25.0.12

  krake_api_ctrl:
    container_name: krake_api_ctrl
    image: krake_api_ctrl
    build:
      context: krake_api_ctrl
    hostname: docker_krake_api_ctrl
    tty: true
    restart: always
    depends_on:
      - krake_db
      - krake_rabbit
    volumes:
      - /home/krake/git/krake:/home/krake/git/krake
      - ./krake_api_ctrl/uwsgi.ini:/etc/uwsgi/uwsgi.ini
      - ./krake_api_ctrl/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    environment:
      - PYTHONPATH=/home/krake/git/krake
      - DEPLOYMENT_CONFIG=/home/krake/git/krake/krake_api/config_dev.py
    networks:
      krake_net:
        ipv4_address: 172.25.0.13

  krake_worker:
    container_name: krake_worker
    image: krake_worker
    build:
      context: krake_worker
    hostname: docker_krake_worker
    tty: true
    restart: always
    depends_on:
      - krake_rabbit
    volumes:
      - /home/krake/git/krake:/home/krake/git/krake
    environment:
      - PYTHONPATH=/home/krake/git/krake
    command: python3 -m krake_worker
    networks:
      krake_net:
        ipv4_address: 172.25.0.14

  krake_scheduler:
    container_name: krake_scheduler
    image: krake_scheduler
    build:
      context: krake_scheduler
    hostname: docker_krake_scheduler
    tty: true
    restart: always
    depends_on:
      - krake_rabbit
    volumes:
      - /home/krake/git/krake:/home/krake/git/krake
    environment:
      - PYTHONPATH=/home/krake/git/krake
    command: python3 -m krake_scheduler
    networks:
      krake_net:
        ipv4_address: 172.25.0.15

networks:
  krake_net:
    driver: bridge
    ipam:
      config:
      - subnet: 172.25.0.0/24
