apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  namespace: infra
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: EnsureExists
data:
  prometheus.yml: |
    global:
      scrape_interval: 60s  # How frequently to scrape targets.
    scrape_configs:
    - job_name: dummy-exporter
      metrics_path: /
      static_configs:
      - targets: ['10.254.0.26:9000']
    - job_name: kubernetes-exporter
      metrics_path: /metrics
      static_configs:
      - targets: ['10.254.0.27:8080']
      metric_relabel_configs:
      - source_labels: [pod]
        regex: '(.*)\-app\-([0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12})\-.*'
        replacement: 'APP-$2'
        target_label: krake_app_uuid
      - source_labels: [pod]
        regex: '(.*)\-app\-([0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12})\-.*'
        replacement: '$1'
        target_label: krake_daemon_name
      - source_labels: [deployment]
        regex: '(.*)\-app\-([0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12})$'
        replacement: 'APP-$2'
        target_label: krake_app_uuid
      - source_labels: [deployment]
        regex: '(.*)\-app\-([0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12})$'
        replacement: '$1'
        target_label: krake_daemon_name
    - job_name: kubernetes-cadvisor
      kubernetes_sd_configs:
      - role: pod
      metric_relabel_configs:
      - source_labels: [container_label_io_kubernetes_pod_name]
        regex: '(.*)\-app\-([0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12})\-.*'
        replacement: 'APP-$2'
        target_label: krake_app_uuid
      - source_labels: [container_label_io_kubernetes_pod_name]
        regex: '(.*)\-app\-([0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12})\-.*'
        replacement: '$1'
        target_label: krake_daemon_name
