---
apiVersion: v1
kind: Pod
metadata:
  name: mnist
  labels:
    app: mnist
spec:
  containers:
    - name: mnist
      image: registry.gitlab.com/alasca.cloud/krake/krake/mnist-e2e-test:ci
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 8080
          name: mnist
        - containerPort: 10000
          name: shutdown
      volumeMounts:
        - mountPath: /krake
          name: mnist-volume
      env:
        - name: HOME
          value: /tmp
      command:
        - /bin/sh
        - -c
        - |
          /bin/sh &
          echo "copy scripts to /tmp (configMap is read-only)"
          cp /krake/mnist-shutdown.py /tmp
          echo "apply 'chmod +x' to /tmp/mnist-shutdown.py"
          chmod +x /tmp/mnist-shutdown.py
          /tmp/mnist-shutdown.py &
          python /mnist/mnist_training.py
  volumes:
    - name: mnist-volume
      configMap:
        name: mnist-shutdown
  restartPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: mnist
spec:
  type: NodePort
  selector:
    app: mnist
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: shutdown
spec:
  type: NodePort
  selector:
    app: mnist
  ports:
  - port: 10000
    protocol: TCP
    targetPort: 10000
