heat_template_version: queens

description: >
  Provision Krake network gateway

parameters:

  instance_name:
    type: string
    default: krake-gateway
    description: Name of the gateway instance

  key:
    type: string
    description: Name of the key pair for gateway instance

  flavor:
    type: string
    description: Name of the flavor to use for the gateway instance
    default: XS

  gateway_secgroup:
    type: string
    default: krake-gateway-secgroup
    description: Name of gateway security group

  public_network:
    type: string
    description: >
      Name of public network for which floating IP addresses will be allocated

  network:
    type: string
    default: krake-network
    description: >
      Name of the private network gateway instances

  subnet:
    type: string
    default: krake-subnet
    description: Name of the private subnetwork for gateway instance

  common_secgroup:
    type: string
    default: krake-common-secgroup
    description: Name of common Krake security group

  use_config_drive:
    type: boolean
    default: false
    description: Control if a config Drive should be used to pass the Metadata to the server

resources:

  instance:
    type: OS::Nova::Server
    properties:
      name: { get_param: instance_name }
      flavor: { get_param: flavor }
      image: e8984d8c-8ae6-498e-8f4a-33afe681615f  # Ubuntu 20.04 LTS x64
      config_drive: { get_param: use_config_drive }
      key_name: { get_param: key }
      networks:
        - port: { get_resource: port }

  port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_param: network }
      fixed_ips:
        - subnet_id: { get_param: subnet }
      security_groups:
        - default
        - { get_param: common_secgroup }
        - { get_resource: security_group }

  floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network_id: { get_param: public_network }
      port_id: { get_resource: port }

outputs:
  private_ip:
    description: IP address of gateway instance in private network
    value: { get_attr: [instance, first_address] }

  public_ip:
    description: Floating IP address of gateway instance
    value: { get_attr: [floating_ip, floating_ip_address] }
