version: '3'

services:

  prometheus_nginx:
    container_name: prometheus_nginx
    image: prometheus_nginx
    build:
      context: prometheus_nginx
      args:
        # Prometheus admin password.
        admin_pass: ${PROMETHEUS_ADMIN_PASS}
    hostname: docker_prometheus_nginx
    tty: true
    restart: always
    volumes:
      # Docker compose relative path is interpreted as relative to the location of the Docker compose file.
      # https://docs.docker.com/compose/compose-file/
      - ./prometheus_nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
    ports:
      - 80:80
      - 443:443
    depends_on:
      - prometheus
      - grafana
      - edit_targets
    networks:
      prometheus_net:
        ipv4_address: 172.25.0.10

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.5.0
    hostname: docker_prometheus
    tty: true
    restart: always
    volumes:
        - ./prometheus/prometheus.yml:/etc/prometheus/krake/prometheus.yml
        - ./prometheus/targets:/etc/prometheus/krake/targets
    command:
        # Web external URL issue:
        # https://github.com/prometheus/prometheus/issues/4925
        - '--config.file=/etc/prometheus/krake/prometheus.yml'
        - '--query.lookback-delta=2m'
        - '--storage.tsdb.path=/prometheus'
        - '--storage.tsdb.retention=48h'
        - '--storage.tsdb.max-block-duration=24h'
        - '--web.enable-admin-api'
        - '--web.external-url=https://localhost:9090/prometheus/'
        - '--web.route-prefix=/'

    networks:
      prometheus_net:
        ipv4_address: 172.25.0.11

  edit_targets:
    container_name: edit_targets
    image: edit_targets
    hostname: docker_edit_targets
    tty: true
    restart: always
    build:
      context: edit_targets
    ports:
      - 8080:8080
    volumes:
      - ./prometheus/targets:/app/edit_targets/krake/targets
    networks:
      prometheus_net:
        ipv4_address: 172.25.0.12

  grafana:
    container_name: grafana
    image: grafana/grafana:6.0.1
    hostname: docker_grafana
    tty: true
    restart: always
    volumes:
        - ./grafana/provisioning:/etc/grafana/provisioning
        - ./grafana/dashboards:/var/lib/grafana/dashboards
    environment:
        # TODO For development purposes only. For production purposes need to be re-visited.
        # Grafana admin password.
        - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASS}
        - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s:%(http_port)s/monitoring/
    depends_on:
        - prometheus
    networks:
      prometheus_net:
        ipv4_address: 172.25.0.13

networks:
  prometheus_net:
    driver: bridge
    ipam:
      config:
      - subnet: 172.25.0.0/24
