---
apiVersion: v1
kind: ConfigMap
metadata:
  name: krake-kubernetes-application
data:
  kubernetes_application.yaml: |
    api_endpoint: http://krake-api:8080
    worker_count: 5
    debounce: 1.0
    hooks:
      complete:
        hook_user: system:complete-hook
        intermediate_src: ""
        intermediate_key_src: ""
        cert_dest: /etc/krake_complete_cert
        env_token: KRAKE_COMPLETE_TOKEN
        env_url: KRAKE_COMPLETE_URL
      shutdown:
        hook_user: system:shutdown-hook
        intermediate_src: ""
        intermediate_key_src: ""
        cert_dest: /etc/krake_shutdown_cert
        env_token: KRAKE_SHUTDOWN_TOKEN
        env_url: KRAKE_SHUTDOWN_URL
    migration:
      retry:
        max: 10
        timeout: 60
    tls:
      enabled: False
      client_ca: ""
      client_cert: ""
      client_key: ""
    log:
      version: 1
      level: INFO
      disable_existing_loggers: false
      formatters:
        krake:
          format: "%(asctime)s - [%(name)s] - [%(levelname)-5s] - %(message)s"
      handlers:
        console:
          class: logging.StreamHandler
          formatter: krake
          stream: ext://sys.stdout
      root:
        handlers: [console]
      loggers:
        krake:
          handlers: [console]
          propagate: no
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: krake-kubernetes-application
  labels:
    app.kubernetes.io/name: krake-kubernetes-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: krake-kubernetes-application
  template:
    metadata:
      labels:
        app.kubernetes.io/name: krake-kubernetes-application
    spec:
      containers:
      - image: raknrok/krake
        name: krake-kubernetes-application
        command:
          - "python"
          - "-m"
          - "krake.controller.kubernetes.application"
        volumeMounts:
        - name: config-volume
          mountPath: /etc/krake
      volumes:
        - name: config-volume
          configMap:
            name: krake-kubernetes-application
