---
apiVersion: v1
kind: ConfigMap
metadata:
  name: krake-scheduler
data:
  scheduler.yaml: |
    api_endpoint: http://krake-api:8080
    worker_count: 5
    debounce: 1.0
    reschedule_after: 60
    stickiness: 0.1
    tls:
      enabled: False
      client_ca: ""
      client_cert: ""
      client_key: ""
    log:
      version: 1
      level: INFO
      disable_existing_loggers: false
      formatters:
        krake:
          format: "%(asctime)s - [%(name)s] - [%(levelname)-5s] - %(message)s"
      handlers:
        console:
          class: logging.StreamHandler
          formatter: krake
          stream: ext://sys.stdout
      root:
        handlers: [console]
      loggers:
        krake:
          handlers: [console]
          propagate: no
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: krake-scheduler
  labels:
    app.kubernetes.io/name: krake-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: krake-scheduler
  template:
    metadata:
      labels:
        app.kubernetes.io/name: krake-scheduler
    spec:
      containers:
      - image: raknrok/krake
        name: krake-scheduler
        command:
          - "python"
          - "-m"
          - "krake.controller.scheduler"
        volumeMounts:
        - name: config-volume
          mountPath: /etc/krake
      volumes:
        - name: config-volume
          configMap:
            name: krake-scheduler
