{
 "title": "Metrics",
 "tags": [
  "krake",
  "deployment",
  "metrics"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "backend",
    "label": "BackEnd",
    "query": "label_values(krake_metric{job=\"dummy-exporter\"}, node)"
   },
   {
    "name": "node",
    "label": "Node name",
    "query": "label_values(krake_metric{job=\"dummy-exporter\", node=~\"$backend\"}, node_name)"
   }
  ]
 },
 "panels": [
  { "title": "Krake Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Krake Metric",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "krake_metric{job=\"dummy-exporter\", node=~\"$backend\", node_name=~\"$node\"}",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  { "title": "Kubernetes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Kubernetes Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "30", "legendFormat": "Kubernetes capacity" },
    {
     "expr": "sum(kube_pod_container_status_running{job=\"kubernetes-exporter\", node=\"Kubernetes\", node_name=~\"$node\"}) by (node_name)",
     "legendFormat": "{{node_name}} pods"
    }
   ]
  },
  { "title": "OpenStack", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "OpenStack Free VCPUs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "openstack_total_free_vcpus{job=\"openstack-exporter\", node=\"OpenStack\", node_name=~\"$node\"}",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "OpenStack Free RAM",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "openstack_total_free_ram_MB{job=\"openstack-exporter\", node=\"OpenStack\", node_name=~\"$node\"}",
     "legendFormat": "{{node_name}}"
    }
   ]
  }
 ]
}