# Compose file defines and runs docker container for provisioning of the Prometheus
# server and metrics exporter server.

version: "3"

services:

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    tty: true
    restart: always
    volumes:
      - ./config:/etc/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/etc/prometheus
      - --storage.tsdb.retention=48h
      - --query.lookback-delta=2m
      - --web.listen-address=${PROMETHEUS_PORT}
    ports:
      - ${PROMETHEUS_PORT}:${PROMETHEUS_PORT}

  metric-exporter:
    image: metric_exporter
    container_name: metric_exporter
    tty: true
    restart: always
    build:
      context: metric_exporter
    command:
      - python3 metric_exporter.py --port ${METRIC_EXPORTER_PORT}
    ports:
      - ${METRIC_EXPORTER_PORT}:${METRIC_EXPORTER_PORT}
