stages:
  - pre
  - lint
  - test
  - e2e
  - release


variables:
  # keep the version according to the official gitlab CI/CD documentation
  # see: https://docs.gitlab.com/ee/ci/docker/using_kaniko.html
  # newer version do not work at the moment
  KANIKO_IMAGE: gcr.io/kaniko-project/executor
  KANIKO_VERSION: v1.14.0-debug


build-ci-image-ansible:
  stage: pre
  image:
    name: "${KANIKO_IMAGE}:${KANIKO_VERSION}"
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n ${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD} | base64)\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "./ci/docker/ansible_runner/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}/ansible_image:latest"
      --verbosity=info
      ## uncomment for debugging purpose:
      #--verbosity=debug
      #--no-push


build-ci-image-pre-commit:
  stage: pre
  image:
    name: "${KANIKO_IMAGE}:${KANIKO_VERSION}"
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n ${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD} | base64)\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --build-arg PYTHON_VER=3.12
      --dockerfile "./ci/docker/test_image/Dockerfile"
      --destination "registry.gitlab.com/rak-n-rok/krake/test_image:3.12"
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --build-arg PYTHON_VER=3.12
      --dockerfile "./ci/docker/pre_commit/Dockerfile"
      --destination "registry.gitlab.com/rak-n-rok/krake/pre_commit_image:latest"
