{
 "title": "API Exporter",
 "description": "Krake API monitoring using Prometheus python client.",
 "tags": [
  "krake",
  "api"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node_name",
    "label": "Node name",
    "query": "label_values(http_requests_total{node=\"Krake\"}, node_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "API Exceptions",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 13, "x": 11, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(krake_api_exceptions_total{node=\"Krake\", worker=~\".*\", node_name=~\"$node_name\"})"
    }
   ]
  },
  { "title": "Create APP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Average request duration during the last 5m",
   "type": "graph",
   "description": "Average request duration during the last 5m",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(krake_api_processing_duration_seconds_sum{node=\"Krake\", node_name=~\"$node_name\", worker=~\".*\", req_type=\"create\", code=~\".*\"}[5m]) * 100) by (node_name)\n/\nsum(rate(krake_api_processing_duration_seconds_count{node=\"Krake\", node_name=~\"$node_name\", worker=~\".*\", req_type=\"create\", code=~\".*\"}[5m]) * 100) by (node_name)",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "HTTP response status code counter",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 4 },
   "targets": [
    {
     "expr": "sum(krake_api_processing_duration_seconds_count{node=\"Krake\", node_name=~\"$node_name\", worker=~\".*\", req_type=\"create\"}) by (code)",
     "legendFormat": "HTTP status code {{code}}"
    }
   ]
  },
  { "title": "Update APP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Average request duration during the last 5m",
   "type": "graph",
   "description": "Average request duration during the last 5m",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(krake_api_processing_duration_seconds_sum{node=\"Krake\", node_name=~\"$node_name\", worker=~\".*\", req_type=\"update\", code=~\".*\"}[5m]) * 100) by (node_name)\n/\nsum(rate(krake_api_processing_duration_seconds_count{node=\"Krake\", node_name=~\"$node_name\", worker=~\".*\", req_type=\"update\", code=~\".*\"}[5m]) * 100) by (node_name)",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "HTTP status codes counter",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 12 },
   "targets": [
    {
     "expr": "sum(krake_api_processing_duration_seconds_count{node=\"Krake\", node_name=~\"$node_name\", worker=~\".*\", req_type=\"update\"}) by (code)",
     "legendFormat": "HTTP status code {{code}}"
    }
   ]
  },
  { "title": "Delete APP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Average request duration during the last 5m",
   "type": "graph",
   "description": "Average request duration during the last 5m",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(krake_api_processing_duration_seconds_sum{node=\"Krake\", node_name=~\"$node_name\", worker=~\".*\", req_type=\"delete\", code=~\".*\"}[5m]) * 100) by (node_name)\n/\nsum(rate(krake_api_processing_duration_seconds_count{node=\"Krake\", node_name=~\"$node_name\", worker=~\".*\", req_type=\"delete\", code=~\".*\"}[5m]) * 100) by (node_name)",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "HTTP status codes counter",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 20 },
   "targets": [
    {
     "expr": "sum(krake_api_processing_duration_seconds_count{node=\"Krake\", node_name=~\"$node_name\", worker=~\".*\", req_type=\"delete\"}) by (code)",
     "legendFormat": "HTTP status code {{code}}"
    }
   ]
  },
  { "title": "List APP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Average request duration during the last 5m",
   "type": "graph",
   "description": "Average request duration during the last 5m",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(krake_api_processing_duration_seconds_sum{node=\"Krake\", node_name=~\"$node_name\", worker=~\".*\", req_type=\"list\", code=~\".*\"}[5m]) * 100) by (node_name)\n/\nsum(rate(krake_api_processing_duration_seconds_count{node=\"Krake\", node_name=~\"$node_name\", worker=~\".*\", req_type=\"list\", code=~\".*\"}[5m]) * 100) by (node_name)",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "HTTP status codes counter",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 28 },
   "targets": [
    {
     "expr": "sum(krake_api_processing_duration_seconds_count{node=\"Krake\", node_name=~\"$node_name\", worker=~\".*\", req_type=\"list\"}) by (code)",
     "legendFormat": "HTTP status code {{code}}"
    }
   ]
  },
  { "title": "Get status APP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Average request duration during the last 5m",
   "type": "graph",
   "description": "Average request duration during the last 5m",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(krake_api_processing_duration_seconds_sum{node=\"Krake\", node_name=~\"$node_name\", worker=~\".*\", req_type=\"get_status\", code=~\".*\"}[5m]) * 100) by (node_name)\n/\nsum(rate(krake_api_processing_duration_seconds_count{node=\"Krake\", node_name=~\"$node_name\", worker=~\".*\", req_type=\"get_status\", code=~\".*\"}[5m]) * 100) by (node_name)",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "HTTP status codes counter",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 36 },
   "targets": [
    {
     "expr": "sum(krake_api_processing_duration_seconds_count{node=\"Krake\", node_name=~\"$node_name\", worker=~\".*\", req_type=\"get_status\"}) by (code)",
     "legendFormat": "HTTP status code {{code}}"
    }
   ]
  }
 ]
}