{
 "title": "Containers Exporter",
 "description": "Container monitoring using Prometheus and cAdvisor",
 "tags": [
  "krake",
  "containers"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "60s",
 "templating": {
  "list": [
   {
    "name": "node_name",
    "label": "Node name",
    "query": "label_values(container_start_time_seconds{node=\"Krake\"}, node_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Running Krake Containers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(container_last_seen{image!='',node_name='$node_name',name=~'krake_.*',node=\"Krake\"})"
    }
   ]
  },
  {
   "title": "Total Krake Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 0 },
   "format": "mbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{image!='',node_name='$node_name',name=~'krake_.*',node=\"Krake\"})/1024/1024"
    }
   ]
  },
  {
   "title": "Total Krake CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_user_seconds_total{image!='',node_name='$node_name',name=~'krake_.*',node=\"Krake\"}[5m]) * 100)"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_user_seconds_total{image!='',node_name='$node_name',name=~'krake_.*',node=\"Krake\"}[5m]) * 100) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{image!='',node_name='$node_name',name=~'krake_.*',node=\"Krake\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Network Rx",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{image!='',node_name='$node_name',name=~'krake_.*',node=\"Krake\"}[5m])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Network Tx",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{image!='',node_name='$node_name',name=~'krake_.*',node=\"Krake\"}[5m])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}