{
 "title": "Deployment statistics Exporter",
 "description": "Krake deployment monitoring using Prometheus python client.",
 "tags": [
  "krake",
  "deployment"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node_name",
    "label": "Node name",
    "query": "label_values(http_requests_total{node=\"Krake\"}, node_name)"
   },
   {
    "name": "deployment_backend",
    "label": "Deployment backend",
    "query": "label_values(krake_applications_total{node=\"Krake\", node_name=~\"$node_name\"}, deployment_backend)"
   },
   {
    "name": "deployment_name",
    "label": "Deployment name",
    "query": "label_values(krake_applications_total{node=\"Krake\", node_name=~\"$node_name\", deployment_backend=~\"$deployment_backend\"}, deployment_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Users counter",
   "type": "singlestat",
   "description": "Tracks the number of Krake users per deployment.\nIn case of multiple Krake nodes We can not guarantee the right number of unique users on Prometheus level.\nTherefore the N/A value is displayed.",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "krake_users_total{node=\"Krake\", node_name=\"$node_name\", deployment_name=\"$deployment_name\", deployment_backend=\"$deployment_backend\"}"
    }
   ]
  },
  {
   "title": "Applications counter",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(krake_applications_total{node=\"Krake\", node_name=~\"$node_name\", deployment_name=~\"$deployment_name\", deployment_backend=~\"$deployment_backend\"}) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Replicas counter",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(krake_replicas_total{node=\"Krake\", node_name=~\"$node_name\", deployment_name=~\"$deployment_name\", deployment_backend=~\"$deployment_backend\"})",
     "legendFormat": "replicas count"
    }
   ]
  }
 ]
}