{
 "title": "Nginx Exporter",
 "description": "Stats exported by Prometheus Nginx plugin",
 "tags": [ "krake" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "60s",
 "templating": {
  "list": [
   {
    "name": "node_name",
    "label": "Node name",
    "query": "label_values(nginx_http_request_duration_seconds_count{node=\"Krake\"}, node_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "HTTP Responses",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(nginx_http_requests_total{node_name=\"$node_name\",node=\"Krake\"}[5m])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_http_request_duration_seconds_sum{node_name=\"$node_name\",node=\"Krake\"}[5m])) / sum(rate(nginx_http_request_duration_seconds_count{node_name=\"$node_name\",node=\"Krake\"}[5m]))"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "nginx_http_connections{state='reading',node_name='$node_name',node=\"Krake\"}",
     "legendFormat": "reading (Connections where NGINX is reading the request header)"
    },
    {
     "expr": "nginx_http_connections{state='writing',node_name='$node_name',node=\"Krake\"}",
     "legendFormat": "writing (Connections where NGINX is writing the response back to the client)"
    },
    {
     "expr": "nginx_http_connections{state='waiting',node_name='$node_name',node=\"Krake\"}",
     "legendFormat": "waiting (Idle client connections)"
    }
   ]
  }
 ]
}