{
 "title": "Node Exporter",
 "description": "Node monitoring using Prometheus and Node Exporter",
 "tags": [
  "krake",
  "node"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "60s",
 "templating": {
  "list": [
   {
    "name": "node_name",
    "label": "Node name",
    "query": "label_values(node_exporter_build_info{node=\"Krake\"},node_name)"
   },
   {
    "name": "node_ip_address",
    "query": "label_values(node_exporter_build_info{node_name='$node_name',node=\"Krake\"}, instance)"
   },
   {
    "name": "cpu_core",
    "query": "label_values(node_cpu{node_name='$node_name',node=\"Krake\"}, cpu)"
   }
  ]
 },
 "panels": [
  {
   "title": "$node_name ($node_ip_address)",
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg"
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(node_time{node_name=~'$node_name',node=\"Krake\"} - node_boot_time{node_name=~'$node_name',node=\"Krake\"})"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 3, "w": 21, "x": 3, "y": 1 }, "content": "\n" },
  {
   "title": "CPU $cpu_core",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
   "repeat": "cpu_core",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100-irate(node_cpu{cpu=~'cpu$cpu_core',mode='idle',node_name=~'$node_name',node=\"Krake\"}[5m])*100",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "repeat": "node",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal{node_name=~'$node_name',node=\"Krake\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "node_memory_Active{node_name=~'$node_name',node=\"Krake\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "node_memory_Cached{node_name=~'$node_name',node=\"Krake\"}",
     "legendFormat": "Cached"
    },
    {
     "expr": "node_memory_Buffers{node_name=~'$node_name',node=\"Krake\"}",
     "legendFormat": "Buffers"
    }
   ]
  },
  {
   "title": "Disk Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "repeat": "node",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_io_time_ms{node_name=~'$node_name',device!~'loop.*',node=\"Krake\"}[5m])/10",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "repeat": "node",
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_network_receive_bytes_total{node_name=~'$node_name'}[5m]))*8 or sum(irate(node_network_receive_bytes{node_name=~'$node_name',node=\"Krake\"}[5m]))*8",
     "legendFormat": "RX"
    },
    {
     "expr": "sum(irate(node_network_transmit_bytes_total{node_name=~'$node_name'}[5m]))*8 or sum(irate(node_network_transmit_bytes{node_name=~'$node_name',node=\"Krake\"}[5m]))*8",
     "legendFormat": "TX"
    }
   ]
  },
  {
   "title": "Disk Space Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "repeat": "node",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100.0 - 100 * (node_filesystem_avail_bytes{node_name=~'$node_name',device!~'tmpfs',device!~'by-uuid',fstype!~'squashfs',node=\"Krake\"} / node_filesystem_size_bytes{node_name=~'$node_name',device !~'tmpfs',device!~'by-uuid',fstype!~'squashfs',node=\"Krake\"}) or 100.0 - 100 * (node_filesystem_avail{node_name=~'$node_name',device !~'tmpfs',device!~'by-uuid',fstype!~'squashfs',node=\"Krake\"} / node_filesystem_size{node_name=~'$node_name',device !~'tmpfs',device!~'by-uuid',fstype!~'squashfs',node=\"Krake\"})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  }
 ]
}