{
 "title": "RabbitMQ Exporter",
 "description": "Rabbitmq stats using RabbitMQ Exporter (https://github.com/kbudde/rabbitmq_exporter)",
 "tags": [ "krake" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "node_name",
    "label": "Node name",
    "query": "label_values(rabbitmq_queue_messages{node=\"Krake\"}, node_name)"
   },
   {
    "name": "rabbit_name",
    "label": "RabbitMQ name",
    "query": "label_values(rabbitmq_node_up{node=\"Krake\"}, name)"
   }
  ]
 },
 "panels": [
  {
   "title": "$rabbit_name",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 0 },
   "repeat": "node",
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "rabbitmq_node_up{node_name=~'$node_name',node=\"Krake\"}"
    }
   ]
  },
  {
   "title": "Global Counts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 3, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_connections{node_name=~'$node_name',node=\"Krake\"}",
     "legendFormat": "Connections"
    },
    {
     "expr": "rabbitmq_channels{node_name=~'$node_name',node=\"Krake\"}",
     "legendFormat": "Channels"
    },
    {
     "expr": "rabbitmq_exchanges{node_name=~'$node_name',node=\"Krake\"}",
     "legendFormat": "Exchanges"
    },
    {
     "expr": "rabbitmq_queues{node_name=~'$node_name',node=\"Krake\"}",
     "legendFormat": "Queues"
    },
    {
     "expr": "rabbitmq_consumers{node_name=~'$node_name',node=\"Krake\"}",
     "legendFormat": "Consumers"
    }
   ]
  },
  {
   "title": "Queued Messages",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rabbitmq_queue_messages_ready{node_name=~'$node_name',node=\"Krake\"})",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum(rabbitmq_queue_messages_unacknowledged{node_name=~'$node_name',node=\"Krake\"})",
     "legendFormat": "Unacked"
    },
    {
     "expr": "sum(rabbitmq_queue_messages{node_name=~'$node_name',node=\"Krake\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Messages per Queue",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_queue_messages{node_name=~'$node_name',node=\"Krake\"}",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Messages status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (queue)(rabbitmq_queue_messages_ready{node_name=~'$node_name',node=\"Krake\"})",
     "legendFormat": "{{queue}}:ready"
    },
    {
     "expr": "sum by (queue)(rabbitmq_queue_messages_published_total{node_name=~'$node_name',node=\"Krake\"})",
     "legendFormat": "{{queue}}:published"
    },
    {
     "expr": "sum by (queue)(rabbitmq_queue_messages_delivered_total{node_name=~'$node_name',node=\"Krake\"})",
     "legendFormat": "{{queue}}:delivered"
    },
    {
     "expr": "sum by (queue)(rabbitmq_queue_messages_unacknowledged{node_name=~'$node_name',node=\"Krake\"})",
     "legendFormat": "{{queue}}:unack"
    }
   ]
  }
 ]
}