- name: Launch Central IdP instances
  hosts: central_idps
  gather_facts: false
  tasks:
    - name: Create Heat stack for Central IdP
      delegate_to: localhost
      os_stack:
        name: "{{ inventory_hostname }}"
        state: present
        template:  "{{ playbook_dir }}/files/central-idp/stack.yml"
        parameters:
          instance_name: "{{ inventory_hostname }}"
          key: "{{ keypair }}"
          central_idp_secgroup: "{{ secgroup_name }}"
          public_network: "{{  hostvars[network]['public_network'] }}"
          network: "{{ hostvars[network]['inventory_hostname'] }}"
          subnet: "{{ hostvars[network]['subnet_name'] }}"
          common_secgroup: "{{ hostvars[network]['common_secgroup_name'] }}"
          git_branch: "{{ git_branch }}"
          create_floating_ip: "{{ floating_ip }}"
          flavor: "{{ flavor }}"
      register: stack

    - name: Update host variables of Central IdP
      vars:
        outputs: "{{ stack | stack_outputs }}"
        jump_host: "{{ hostvars[gateway].ansible_user }}@{{ hostvars[gateway].ansible_host }}"
        jump_key_file: "{{ hostvars[gateway].ansible_ssh_private_key_file }}"
      update_host:
        hostname: "{{ inventory_hostname }}"
        ansible_host: "{{ outputs.private_ip }}"
        ansible_ssh_private_key_file: "{{ key_file }}"
        ansible_ssh_common_args: '
          -o StrictHostKeyChecking=No
          -o UserKnownHostsFile=/dev/null
          -o ProxyCommand="ssh
              -o StrictHostKeyChecking=No
              -o UserKnownHostsFile=/dev/null
              {% if jump_key_file %} -i {{ jump_key_file }} {% endif %}
              -W %h:%p -q {{ jump_host }}"'
        ansible_user: ubuntu
        ansible_python_interpreter: python3
        private_ip: "{{ outputs.private_ip }}"
        public_ip: "{{ outputs.public_ip | default(None) }}"

- name: Wait for cloud-init to finish on Central IdP instances
  hosts: central_idps
  gather_facts: false
  roles:
    - cloud-init
    - authorized-keys
  vars:
    authorized_user: ubuntu
