- name: Running Krake integration tests
  become: yes
  become_user: krake
  hosts: krake_apps
  vars:
    git_dir: /home/krake/git/krake
    test_dir: rak/functionals
  tasks:
    - name: Install Tests dependencies
      pip:
        name: "{{ git_dir }}/rak/[test]"
        state: present
        executable: pip3
        extra_args: --user
      environment:
        PATH: "{{ ansible_env.PATH }}:{{ ansible_env.HOME }}/.local/bin"

    # We need one Minikube cluster in order to run the integration tests
    - name: Check if a Minikube clusters have been spawned
      assert:
        that:
          - "groups['minikube_clusters'][0] is defined"
          - "groups['minikube_clusters'][1] is defined"

    # pytest and rok are installed locally in /home/krake/.local/bin which
    # isn't in the default PATH
    - name: Run integration tests for the scheduling algorithm
      command: "pytest {{ git_dir }}/{{test_dir}}/integration/test_scheduling.py --minikubeclusters {{ groups['minikube_clusters'][0] }} {{ groups['minikube_clusters'][1] }}"
      environment:
        PATH: "{{ ansible_env.PATH }}:{{ansible_env.HOME}}/.local/bin"

    - name: Run integration tests for the Krake k8s resources update
      command: "pytest {{ git_dir }}/{{test_dir}}/integration/test_update.py --minikubeclusters {{ groups['minikube_clusters'][0] }} {{ groups['minikube_clusters'][1] }}"
      environment:
        PATH: "{{ ansible_env.PATH }}:{{ansible_env.HOME}}/.local/bin"

    - name: Run integration tests for the Kubernetes Observer
      command: "pytest {{ git_dir }}/{{test_dir}}/integration/test_kubernetes_observer.py --minikubeclusters {{ groups['minikube_clusters'][0] }} {{ groups['minikube_clusters'][1] }}"
      environment:
        PATH: "{{ ansible_env.PATH }}:{{ansible_env.HOME}}/.local/bin"

    - name: Run integration tests for krake scripts
      command: "pytest {{ git_dir }}/{{test_dir}}/integration/test_scripts.py --krake_container {{ api_host }} --etcd_container {{ etcd_host }} --etcd_container_port {{ etcd_port }}"
      environment:
        PATH: "{{ ansible_env.PATH }}:{{ansible_env.HOME}}/.local/bin"
