- name: Setup Kubernetes keystone auth
  hosts: minikube_clusters
  vars:
    minikube: true
    user_role: "_member_"
    user_project: "demo"
    k8s_path: "/etc/kubernetes"
    k8s_auth_dir: "/home/ubuntu/k8s_auth"
    k8s_config: "/home/ubuntu/.kube/config"
    k8s_api_config: "{{ k8s_path }}/manifests/kube-apiserver.yaml"
    k8s_path_minikube: "/var/lib/minikube/certs"
  roles:
    - k8s-keystone-auth
