# Top-level Ansible playbook for complete provisioning of the Krake
# infrastructure.

# The configuration and dynamic inventory is managed in a central
# configuration file. An example inventory is given in "hosts.example". The
# playbook is called as follows:
#
#   ansible-playbook -i hosts site.yml
#
- import_playbook: network.yml
- import_playbook: gateway.yml
- import_playbook: minikube_cluster.yml
- import_playbook: k3s_cluster.yml
- import_playbook: microk8s_cluster.yml
- import_playbook: krake.yml
- import_playbook: krake_handle_certs.yml
