- name: Running Krake smoke tests
  become: yes
  become_user: krake
  hosts: krake_apps
  vars:
    git_dir: /home/krake/git/krake
    test_dir: rak/functionals
  tasks:
    - name: Install Tests dependencies
      pip:
        name: "{{ git_dir }}/rak/[test]"
        state: present
        executable: pip3
        extra_args: --user
      environment:
        PATH: "{{ ansible_env.PATH }}:{{ ansible_env.HOME }}/.local/bin"

    # pytest and rok are installed locally in /home/krake/.local/bin which
    # isn't in the default PATH
    - name: Run smoke test for krake client
      command: "pytest {{ git_dir }}/{{ test_dir }}/test_krake_cli.py"
      environment:
        PATH: "{{ ansible_env.PATH }}:{{ ansible_env.HOME }}/.local/bin"


- name: Running smoke tests on minikube
  hosts: minikube_clusters
  vars:
    home_dir: /home/ubuntu
    test_dir: rak/functionals
  tasks:

    - name: smoke minikube clusters
      block:

        - name: Ensure rak directory is present
          copy:
            src: "{{ playbook_dir }}/../rak/"
            dest: "{{ home_dir }}/rak/"

        - name: Install Tests dependencies
          pip:
            name: "{{ home_dir }}/rak/[test]"
            state: present
            executable: pip3
            extra_args: --user
          environment:
            PATH: "{{ ansible_env.PATH }}:{{ ansible_env.HOME }}/.local/bin"

        # pytest and rok are installed locally in /home/ubuntu/.local/bin which
        # isn't in the default PATH
        - name: Run smoke test for Minikube
          command: "pytest {{ home_dir }}/{{ test_dir }}/test_kubektl_cli.py"
          environment:
            PATH: "{{ ansible_env.PATH }}:{{ ansible_env.HOME }}/.local/bin"

      when: groups['minikube_clusters'] is defined


- name: Running smoke tests on k3s
  hosts: k3s_clusters
  vars:
    home_dir: /home/ubuntu
    test_dir: rak/functionals
  tasks:

    - name: smoke k3s clusters
      block:

        - name: Ensure rak directory is present
          copy:
            src: "{{ playbook_dir }}/../rak/"
            dest: "{{ home_dir }}/rak/"

        - name: Install Tests dependencies
          pip:
            name: "{{ home_dir }}/rak/[test]"
            state: present
            executable: pip3
            extra_args: --user
          environment:
            PATH: "{{ ansible_env.PATH }}:{{ ansible_env.HOME }}/.local/bin"

        # pytest and rok are installed locally in /home/ubuntu/.local/bin which
        # isn't in the default PATH
        - name: Run smoke test for k3s
          command: "pytest {{ home_dir }}/{{ test_dir }}/test_kubectl_cli.py"
          environment:
            PATH: "{{ ansible_env.PATH }}:{{ ansible_env.HOME }}/.local/bin"

      when: groups['k3s_clusters'] is defined
