- name: Running Krake smoke tests
  become: yes
  become_user: krake
  hosts: krake_apps
  vars:
    git_dir: /home/krake/git/krake
    test_dir: tests
  tasks:
    - name: Install pytest
      pip:
        name:
          - pytest
        state: present

    # pytest and rok are installed locally in /home/krake/.local/bin which
    # isn't in the default PATH
    - name: Run smoke test for krake client
      command: "pytest {{ git_dir }}/{{test_dir}}/test_krake_cli.py"
      environment:
        PATH: "{{ ansible_env.PATH }}:{{ansible_env.HOME}}/.local/bin"


- name: Running Minikube smoke tests
  hosts: minikube_clusters
  vars:
    home_dir: /home/ubuntu
    test_dir: tests
  tasks:
    - name: Install pytest
      pip:
        name:
          - pytest
        state: present

    - name: Ensure Minikube smoke test is present
      copy:
        src: ../tests/
        dest: tests/

    # pytest and rok are installed locally in /home/ubuntu/.local/bin which
    # isn't in the default PATH
    - name: Run smoke test for Minikube
      command: "pytest {{ home_dir }}/{{test_dir}}/test_minikube_cli.py"
      environment:
        PATH: "{{ ansible_env.PATH }}:{{ansible_env.HOME}}/.local/bin"