- name: Unprovision infrastructure
  hosts: all
  strategy: free
  gather_facts: false
  tasks:

    - name: Delete Heat stack
      delegate_to: localhost
      os_stack:
        name: "{{ inventory_hostname }}"
        state: absent

    - name: Clean host variables
      delete_host:
        hostname: "{{ inventory_hostname }}"
