---
- hosts: exporters
  become: yes
  roles:
    - role-dummy-exporter
    - role-openstack-exporter

- hosts: prometheus
  become: yes
  roles:
    - role-prometheus

- hosts: nginx-proxy
  become: yes
  roles:
    - role-nginx-proxy
