{
 "title": "Apps",
 "description": "Docker monitoring with Prometheus and cAdvisor",
 "tags": [
  "krake",
  "apps"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "krake_app",
    "label": "Application",
    "query": "label_values(container_start_time_seconds{node=\"Kubernetes\", job=\"kubernetes-cadvisor\"}, krake_app_uuid)"
   },
   {
    "name": "krake_daemon",
    "label": "Daemon",
    "query": "label_values(container_start_time_seconds{node=\"Kubernetes\", job=\"kubernetes-cadvisor\", krake_app_uuid=~\"$krake_app\"}, krake_daemon_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Running Pods/Requested Pods",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(kube_pod_status_phase{node=\"Kubernetes\", job=\"kubernetes-exporter\", krake_app_uuid=~\"$krake_app\", krake_daemon_name=~\"$krake_daemon\", phase=\"Running\", namespace!~\"infra|kube-system\"}) / sum(kube_deployment_status_replicas{node=\"Kubernetes\", job=\"kubernetes-exporter\", krake_app_uuid=~\"$krake_app\", krake_daemon_name=~\"$krake_daemon\", namespace!~\"infra|kube-system\"})* 100)"
    }
   ]
  },
  {
   "title": "Containers UPTIME",
   "type": "table",
   "gridPos": { "h": 5, "w": 9, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "time() - avg(container_start_time_seconds{node=\"Kubernetes\", job=\"kubernetes-cadvisor\", krake_app_uuid=~\"$krake_app\", krake_daemon_name=~\"$krake_daemon\", container_label_io_kubernetes_container_name!~\"POD\", container_label_io_kubernetes_pod_namespace!~\"infra|kube-system\", image!=\"\"}) by (id)",
     "legendFormat": "docker:/{{id}}"
    }
   ]
  },
  {
   "title": "Containers Running Images [5m]",
   "type": "table",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 0 },
   "targets": [
    {
     "expr": "avg(kube_pod_container_info{node=\"Kubernetes\", job=\"kubernetes-exporter\", krake_app_uuid=~\"$krake_app\", krake_daemon_name=~\"$krake_daemon\", namespace!~\"infra|kube-system\"}) by (container_id, image)"
    }
   ]
  },
  { "title": "Daemon Pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Pods Running",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{node=\"Kubernetes\", job=\"kubernetes-exporter\", krake_app_uuid=~\"$krake_app\", krake_daemon_name=~\"$krake_daemon\", phase=\"Running\", namespace!~\"infra|kube-system\"})"
    }
   ]
  },
  {
   "title": "Pods Pending",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{node=\"Kubernetes\", job=\"kubernetes-exporter\", krake_app_uuid=~\"$krake_app\", krake_daemon_name=~\"$krake_daemon\", phase=\"Pending\", namespace!~\"infra|kube-system\"})"
    }
   ]
  },
  {
   "title": "Pods Failed",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{node=\"Kubernetes\", job=\"kubernetes-exporter\", krake_app_uuid=~\"$krake_app\", krake_daemon_name=~\"$krake_daemon\", phase=\"Failed\", namespace!~\"infra|kube-system\"})"
    }
   ]
  },
  {
   "title": "Pods Succeeded",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{node=\"Kubernetes\", job=\"kubernetes-exporter\", krake_app_uuid=~\"$krake_app\", krake_daemon_name=~\"$krake_daemon\", phase=\"Succeeded\", namespace!~\"infra|kube-system\"})"
    }
   ]
  },
  {
   "title": "Pods Unknown",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{node=\"Kubernetes\", job=\"kubernetes-exporter\", krake_app_uuid=~\"$krake_app\", krake_daemon_name=~\"$krake_daemon\", phase=\"Unknown\", namespace!~\"infra|kube-system\"})"
    }
   ]
  },
  { "title": "Daemon Containers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Containers Running ",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 13 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(container_last_seen{node=\"Kubernetes\", job=\"kubernetes-cadvisor\", krake_app_uuid=~\"$krake_app\", krake_daemon_name=~\"$krake_daemon\", container_label_io_kubernetes_container_name!~\"POD\", container_label_io_kubernetes_pod_namespace!~\"infra|kube-system\", image!=\"\"})"
    }
   ]
  },
  {
   "title": "Containers Waiting",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 13 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_waiting{node=\"Kubernetes\", job=\"kubernetes-exporter\", krake_app_uuid=~\"$krake_app\", krake_daemon_name=~\"$krake_daemon\", namespace!~\"infra|kube-system\"})"
    }
   ]
  },
  {
   "title": "Containers Terminated",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 13 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_terminated{node=\"Kubernetes\", job=\"kubernetes-exporter\", krake_app_uuid=~\"$krake_app\", krake_daemon_name=~\"$krake_daemon\", namespace!~\"infra|kube-system\"})"
    }
   ]
  },
  {
   "title": "Containers Restarts (Last 30 Minutes)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 13 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(delta(kube_pod_container_status_restarts_total{job=\"kubernetes-exporter\", node=\"Kubernetes\", krake_app_uuid=~\"$krake_app\", krake_daemon_name=~\"$krake_daemon\", namespace!~\"infra|kube-system\"}[30m]))"
    }
   ]
  },
  { "title": "Daemon Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Total CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 17 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{node=\"Kubernetes\", job=\"kubernetes-cadvisor\", krake_app_uuid=~\"$krake_app\", krake_daemon_name=~\"$krake_daemon\", container_label_io_kubernetes_pod_namespace!~\"infra|kube-system\", image!=\"\"}[5m]) * 100)"
    }
   ]
  },
  {
   "title": "CPU Cores Requested by Containers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 17 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{job=\"kubernetes-exporter\", node=\"Kubernetes\", krake_app_uuid=~\"$krake_app\", krake_daemon_name=~\"$krake_daemon\", namespace!~\"infra|kube-system\"})"
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 17 },
   "format": "mbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{node=\"Kubernetes\", job=\"kubernetes-cadvisor\", krake_app_uuid=~\"$krake_app\", krake_daemon_name=~\"$krake_daemon\", container_label_io_kubernetes_container_name!~\"POD\", container_label_io_kubernetes_pod_namespace!~\"infra|kube-system\", image!=\"\"})/1024/1024"
    }
   ]
  },
  {
   "title": "Memory Requested By Containers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 17 },
   "format": "mbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{node=\"Kubernetes\", job=\"kubernetes-exporter\", krake_app_uuid=~\"$krake_app\", krake_daemon_name=~\"$krake_daemon\", namespace!~\"infra|kube-system\"})"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_user_seconds_total{node=\"Kubernetes\", job=\"kubernetes-cadvisor\", krake_app_uuid=~\"$krake_app\", krake_daemon_name=~\"$krake_daemon\", container_label_io_kubernetes_pod_namespace!~\"infra|kube-system\", image!=\"\"}[5m]) * 100) by (krake_daemon_name)",
     "legendFormat": "cpu-user"
    },
    {
     "expr": "sum(rate(container_cpu_system_seconds_total{node=\"Kubernetes\", job=\"kubernetes-cadvisor\", krake_app_uuid=~\"$krake_app\", krake_daemon_name=~\"$krake_daemon\", container_label_io_kubernetes_pod_namespace!~\"infra|kube-system\", image!=\"\"}[5m]) * 100) by (krake_daemon_name)",
     "legendFormat": "cpu-system"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{node=\"Kubernetes\", job=\"kubernetes-cadvisor\", krake_app_uuid=~\"$krake_app\", krake_daemon_name=~\"$krake_daemon\", container_label_io_kubernetes_pod_namespace!~\"infra|kube-system\", image!=\"\"}[5m]) * 100) by (krake_daemon_name)",
     "legendFormat": "cpu-total"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{node=\"Kubernetes\", job=\"kubernetes-cadvisor\", krake_app_uuid=~\"$krake_app\", krake_daemon_name=~\"$krake_daemon\", container_label_io_kubernetes_container_name!~\"POD\", container_label_io_kubernetes_pod_namespace!~\"infra|kube-system\", image!=\"\"}) by (krake_daemon_name)"
    }
   ]
  },
  {
   "title": "Disk Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_fs_writes_bytes_total{node=\"Kubernetes\", job=\"kubernetes-cadvisor\", krake_app_uuid=~\"$krake_app\", krake_daemon_name=~\"$krake_daemon\", container_label_io_kubernetes_container_name!~\"POD\", container_label_io_kubernetes_pod_namespace!~\"infra|kube-system\", image!=\"\"}) by (krake_daemon_name, device)",
     "legendFormat": "write {{device}}"
    },
    {
     "expr": "sum(container_fs_reads_bytes_total{node=\"Kubernetes\", job=\"kubernetes-cadvisor\", krake_app_uuid=~\"$krake_app\", krake_daemon_name=~\"$krake_daemon\", container_label_io_kubernetes_container_name!~\"POD\", container_label_io_kubernetes_pod_namespace!~\"infra|kube-system\", image!=\"\"}) by (krake_daemon_name, device)",
     "legendFormat": "read {{device}}"
    }
   ]
  },
  {
   "title": "Network Rx/Tx",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{node=\"Kubernetes\", job=\"kubernetes-cadvisor\", krake_app_uuid=~\"$krake_app\", krake_daemon_name=~\"$krake_daemon\", container_label_io_kubernetes_pod_namespace!~\"infra|kube-system\", image!=\"\"}[5m])) by (krake_daemon_name)",
     "legendFormat": "RX"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{node=\"Kubernetes\", job=\"kubernetes-cadvisor\", krake_app_uuid=~\"$krake_app\", krake_daemon_name=~\"$krake_daemon\", container_label_io_kubernetes_pod_namespace!~\"infra|kube-system\", image!=\"\"}[5m])) by (krake_daemon_name)",
     "legendFormat": "TX"
    }
   ]
  },
  {
   "title": "Network Errors/Drops",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_packets_dropped_total{node=\"Kubernetes\", job=\"kubernetes-cadvisor\", krake_app_uuid=~\"$krake_app\", krake_daemon_name=~\"$krake_daemon\", container_label_io_kubernetes_pod_namespace!~\"infra|kube-system\", image!=\"\"}[5m])) by (krake_daemon_name)",
     "legendFormat": "Drops RX"
    },
    {
     "expr": "sum(rate(container_network_transmit_packets_dropped_total{node=\"Kubernetes\", job=\"kubernetes-cadvisor\", krake_app_uuid=~\"$krake_app\", krake_daemon_name=~\"$krake_daemon\", container_label_io_kubernetes_pod_namespace!~\"infra|kube-system\", image!=\"\"}[5m])) by (krake_daemon_name)",
     "legendFormat": "Drops TX"
    },
    {
     "expr": "sum(rate(container_network_receive_errors_total{node=\"Kubernetes\", job=\"kubernetes-cadvisor\", krake_app_uuid=~\"$krake_app\", krake_daemon_name=~\"$krake_daemon\", container_label_io_kubernetes_pod_namespace!~\"infra|kube-system\", image!=\"\"}[5m])) by (krake_daemon_name)",
     "legendFormat": "Errors RX"
    },
    {
     "expr": "sum(rate(container_network_transmit_errors_total{node=\"Kubernetes\", job=\"kubernetes-cadvisor\", krake_app_uuid=~\"$krake_app\", krake_daemon_name=~\"$krake_daemon\", container_label_io_kubernetes_pod_namespace!~\"infra|kube-system\", image!=\"\"}[5m])) by (krake_daemon_name)",
     "legendFormat": "Errors TX"
    }
   ]
  }
 ]
}