---
- name: Create configuration directory
  file:
    path: /opt/docker-mounts/prometheus/config
    state: directory
    mode: u=rwx,g=rx,o=rx

- name: Create config file directories
  file:
    path: /opt/docker-mounts/prometheus/config/{{ item.key | dirname }}
    state: directory
    mode: u=rwx,g=rx,o=rx
  with_dict: "{{ prometheus_config_files }}"

- name: Write config files
  copy:
    dest: /opt/docker-mounts/prometheus/config/{{ item.key }}
    content: '{{ item.value }}'
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  with_dict: "{{ prometheus_config_files }}"
  notify: prometheus_reload_config

- name: Write configuration
  copy:
    dest: /opt/docker-mounts/prometheus/config/prometheus.yml
    content: '{{ prometheus_config|to_nice_yaml }}'
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  notify: prometheus_reload_config
