---
- name: Create and start Prometheus container
  docker_container:
    name: "{{ prometheus_container_name }}"
    image: "{{ prometheus_image_name }}:{{ prometheus_image_tag }}"
    entrypoint: "{{ prometheus_entrypoint }}"
    command: "{{ prometheus_command }}"
    detach: yes
    exposed_ports: "{{ prometheus_port }}:{{ prometheus_port }}"
    restart_policy: always
    volumes:
    - prometheus-data:/prometheus
    - /opt/docker-mounts/prometheus/config:/etc/prometheus
    state: started
    networks:
      - name: "{{ docker_network }}"
        ipv4_address: "{{ prometheus_ip }}"
  register: prometheus_container
