---
apiVersion: v1
kind: Pod
metadata:
  name: etcdctl
  labels:
    app.kubernetes.io/name: debian
spec:
  containers:
  - image: bitnami/etcd:latest
    imagePullPolicy: IfNotPresent
    name: etcdctl
    command: ["tail", "-f", "/dev/null"]
