---
apiVersion: v1
kind: Pod
metadata:
  name: etcdctl
  namespace: development
  labels:
    app.kubernetes.io/name: debian
spec:
  containers:
  - name: etcdctl
    image: bitnami/etcd:latest
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
        cpu: "200m"
    imagePullPolicy: IfNotPresent
    command: ["tail", "-f", "/dev/null"]
