---
apiVersion: v1
kind: Pod
metadata:
  name: etcdctl
  namespace: development
  labels:
    environment: development
    app.kubernetes.io/name: etcdctl
    app.kubernetes.io/instance: etcd-zeutcr
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/component: tools
    app.kubernetes.io/part-of: krake
spec:
  containers:
  - name: etcdctl
    image: bitnami/etcd:latest
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
        cpu: "200m"
    imagePullPolicy: IfNotPresent
    command: ["tail", "-f", "/dev/null"]
